name: My Simple Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'your name'
        required: true
        default: 'World'
      greeting:
        description: 'greeting'
        required: false
        default: 'Hello'
      time:
        description: 'time'
        required: false
        default: '2025'
      file_path: 
        description: 'Path to the file in the submodule'
        required: true
        default: 'test-data/test-data.txt'


jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: print greeting
        run: |
          echo "${{ github.event.inputs.greeting }}, ${{ github.event.inputs.name }}! ${{ github.event.inputs.time }}"
     
  
  read:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Read file from submodule
        id: read_file
        run: |
          FILE_PATH="${{ github.event.inputs.file_path }}"
          echo "File content:"
          cat "$FILE_PATH"

