name: My Simple Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'your name'
        required: true
        default: 'World'
      greeting:
        description: 'greeting'
        required: false
        default: 'Hello'
      time:
        description: 'time'
        required: false
        default: '2025'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "${{ github.event.inputs.greeting }}, ${{ github.event.inputs.name }}! ${{ github.event.inputs.time }}"
